export const GLOBAL_CHECK_LOGIN = 'GLOBAL_CHECK_LOGIN';

export const GLOBAL_LOGIN = 'GLOBAL_LOGIN';
export const GLOBAL_LOGIN_SUCCESS = 'GLOBAL_LOGIN_SUCCESS';
export const GLOBAL_LOGIN_FAIL = 'GLOBAL_LOGIN_FAIL';
export const GLOBAL_LOGOUT = 'GLOBAL_LOGOUT';
export const GLOBAL_LOGOUT_SUCCESS = 'GLOBAL_LOGOUT_SUCCESS';
export const GLOBAL_LOGOUT_FAIL = 'GLOBAL_LOGOUT_FAIL';
export const GLOBAL_LOGIN_SESSION_EXPIRED = 'GLOBAL_LOGIN_SESSION_EXPIRED';

// component behaviors
export const GLOBAL_CLOSE_TOAST = 'GLOBAL_CLOSE_TOAST';