// hardware crud
export const HARDWARE_GET = 'HARDWARE_GET';
export const HARDWARE_GET_SUCCESS = 'HARDWARE_GET_SUCCESS';
export const HARDWARE_GET_FAIL = 'HARDWARE_GET_FAIL';
export const HARDWARE_ADD = 'HARDWARE_ADD';
export const HARDWARE_ADD_SUCCESS = 'HARDWARE_ADD_SUCCESS';
export const HARDWARE_ADD_FAIL = 'HARDWARE_ADD_FAIL';
export const HARDWARE_EDIT = 'HARDWARE_EDIT';
export const HARDWARE_EDIT_SUCCESS = 'HARDWARE_EDIT_SUCCESS';
export const HARDWARE_EDIT_FAIL = 'HARDWARE_EDIT_FAIL';
export const HARDWARE_DELETE = 'HARDWARE_DELETE';
export const HARDWARE_DELETE_SUCCESS = 'HARDWARE_DELETE_SUCCESS';
export const HARDWARE_DELETE_FAIL = 'HARDWARE_DELETE_FAIL';

// check in/out hardware
export const HARDWARE_CHECK_IN = 'HARDWARE_CHECK_IN';
export const HARDWARE_CHECK_IN_SUCCESS = 'HARDWARE_CHECK_IN_SUCCESS';
export const HARDWARE_CHECK_IN_FAIL = 'HARDWARE_CHECK_IN_FAIL';
export const HARDWARE_CHECK_OUT = 'HARDWARE_CHECK_OUT';
export const HARDWARE_CHECK_OUT_SUCCESS = 'HARDWARE_CHECK_OUT_SUCCESS';
export const HARDWARE_CHECK_OUT_FAIL = 'HARDWARE_CHECK_OUT_FAIL';