// project crud
export const PROJECT_GET = 'PROJECT_GET';
export const PROJECT_GET_SUCCESS = 'PROJECT_GET_SUCCESS';
export const PROJECT_GET_FAIL = 'PROJECT_GET_FAIL';
export const PROJECT_ADD = 'PROJECT_ADD';
export const PROJECT_ADD_SUCCESS = 'PROJECT_ADD_SUCCESS';
export const PROJECT_ADD_FAIL = 'PROJECT_ADD_FAIL';
export const PROJECT_EDIT = 'PROJECT_EDIT';
export const PROJECT_EDIT_SUCCESS = 'PROJECT_EDIT_SUCCESS';
export const PROJECT_EDIT_FAIL = 'PROJECT_EDIT_FAIL';
export const PROJECT_DELETE = 'PROJECT_DELETE';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';
export const PROJECT_DELETE_FAIL = 'PROJECT_DELETE_FAIL';

// join/leave project
export const PROJECT_JOIN = 'PROJECT_JOIN';
export const PROJECT_JOIN_SUCCESS = 'PROJECT_JOIN_SUCCESS';
export const PROJECT_JOIN_FAIL = 'PROJECT_JOIN_FAIL';
export const PROJECT_LEAVE = 'PROJECT_LEAVE';
export const PROJECT_LEAVE_SUCCESS = 'PROJECT_LEAVE_SUCCESS';
export const PROJECT_LEAVE_FAIL = 'PROJECT_LEAVE_FAIL';

// component behaviors
export const PROJECT_OPEN_DETAIL_MODAL = 'PROJECT_OPEN_DETAIL_MODAL';
export const PROJECT_CLOSE_DETAIL_MODAL = 'PROJECT_CLOSE_DETAIL_MODAL';
